# Generated by Django 5.0.1 on 2024-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ssd', models.CharField(max_length=50)),
                ('websites', models.IntegerField()),
                ('subdomains', models.IntegerField()),
                ('databases', models.IntegerField()),
                ('ram', models.CharField(max_length=50)),
                ('period', models.IntegerField(choices=[(1, '1 місяць'), (3, '3 місяці'), (6, '6 місяців'), (12, '12 місяців')])),
            ],
        ),
    ]
