# Generated by Django 5.0.1 on 2024-05-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
