# Generated by Django 5.0.1 on 2024-05-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='period',
        ),
    ]
