# Generated by Django 5.0.1 on 2024-05-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0006_product_web'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_web',
            new_name='Product_vps_hosting',
        ),
    ]
