# Generated by Django 5.0.1 on 2024-05-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0008_product_cloud_hosting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_cloud_hosting',
        ),
    ]
