# Generated by Django 5.0.1 on 2024-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0009_delete_product_cloud_hosting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_cloud_hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vcpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=20)),
                ('ssd', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
            ],
        ),
    ]
