# Generated by Django 5.0.1 on 2024-05-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0010_product_cloud_hosting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_vps_hosting',
            new_name='Product_web_hosting',
        ),
    ]
