# Generated by Django 5.0.1 on 2024-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0014_delete_product_web_hosting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_vps_hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ssd', models.CharField(max_length=50)),
                ('websites', models.IntegerField()),
                ('subdomains', models.IntegerField()),
                ('databases', models.IntegerField()),
                ('ram', models.CharField(max_length=20)),
            ],
        ),
    ]
