# Generated by Django 5.0.1 on 2024-05-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0015_product_vps_hosting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_virtual_hosting',
        ),
    ]
