# Generated by Django 5.0.1 on 2024-05-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0016_rename_product_product_virtual_hosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='databases',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='ram',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='ssd',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='subdomains',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='websites',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
