# Generated by Django 5.0.1 on 2024-05-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0017_alter_product_virtual_hosting_databases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='databases',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='ram',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='ssd',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='subdomains',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='websites',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
