# Generated by Django 5.0.1 on 2024-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0019_alter_product_vps_hosting_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
