# Generated by Django 5.0.1 on 2024-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0021_alter_product_vps_hosting_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cloud_hosting',
            name='ram',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_cloud_hosting',
            name='ssd',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_cloud_hosting',
            name='vcpu',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
