# Generated by Django 5.0.1 on 2024-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0022_alter_product_cloud_hosting_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cloud_hosting',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_cloud_hosting',
            name='ssd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_cloud_hosting',
            name='vcpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='databases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='ssd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='subdomains',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='websites',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='databases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='ssd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='subdomains',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='websites',
            field=models.IntegerField(),
        ),
    ]
