# Generated by Django 5.0.1 on 2024-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0023_alter_product_cloud_hosting_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_virtual_hosting',
            name='ssl',
            field=models.CharField(blank=True, choices=[('yes', 'Так'), ('no', 'Ні')], max_length=3),
        ),
    ]
