# Generated by Django 5.0.1 on 2024-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0026_alter_product_virtual_hosting_rent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_virtual_hosting',
            name='rent_duration',
            field=models.CharField(blank=True, choices=[('1_month', '1місяць'), ('3_months', '3 місяці'), ('6_months', '6 місяців'), ('12_months', '12 місяців')], max_length=100),
        ),
    ]
