# Generated by Django 5.0.1 on 2024-05-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0027_alter_product_virtual_hosting_rent_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_virtual_hosting',
            name='rent_duration',
        ),
    ]
