# Generated by Django 5.0.1 on 2024-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0029_alter_product_virtual_hosting_ssl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_vps_hosting',
            old_name='databases',
            new_name='vcpu',
        ),
        migrations.RemoveField(
            model_name='product_vps_hosting',
            name='subdomains',
        ),
        migrations.RemoveField(
            model_name='product_vps_hosting',
            name='websites',
        ),
        migrations.AddField(
            model_name='product_vps_hosting',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
