# Generated by Django 5.0.1 on 2024-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_page', '0030_rename_databases_product_vps_hosting_vcpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_vps_hosting',
            name='os',
            field=models.CharField(max_length=50),
        ),
    ]
