# Generated by Django 5.0.1 on 2024-05-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='ssl',
            field=models.CharField(choices=[('yes', 'Так'), ('no', 'Ні')], max_length=3),
        ),
    ]
