# Generated by Django 5.0.1 on 2024-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_storage', '0003_supportoption_alter_product_ftp_storage_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_ftp_storage',
            name='support',
        ),
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='capacity',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='SupportOption',
        ),
        migrations.AddField(
            model_name='product_ftp_storage',
            name='support',
            field=models.CharField(choices=[('email', 'Електронна пошта'), ('phone', 'Телефон'), ('email_phone', 'Електронна пошта або 24/7 телефон, чат, елекронна пошта')], default='email', max_length=50),
        ),
    ]
