# Generated by Django 5.0.1 on 2024-05-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_storage', '0004_remove_product_ftp_storage_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='support',
            field=models.CharField(choices=[('email', 'Електронна пошта'), ('phone', 'Телефон'), ('email_phone', 'Електронна пошта або 24/7 телефон, чат, елекронна пошта')], max_length=50),
        ),
    ]
