# Generated by Django 5.0.1 on 2024-05-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_storage', '0008_alter_product_ftp_storage_data_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ftp_storage',
            name='rent_duration',
            field=models.CharField(blank=True, choices=[('1_month', '1 місяць')], max_length=20),
        ),
    ]
