# Generated by Django 5.0.1 on 2024-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_storage', '0013_alter_product_ftp_storage_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='rent_duration',
            field=models.CharField(choices=[('1_month', '1 місяць')], max_length=20),
        ),
    ]
