# Generated by Django 5.0.1 on 2024-05-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_storage', '0014_alter_product_ftp_storage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='rent_duration',
            field=models.CharField(blank=True, choices=[('1_month', '1 місяць')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='ssl',
            field=models.CharField(blank=True, choices=[('yes', 'Так'), ('no', 'Ні')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product_ftp_storage',
            name='support',
            field=models.CharField(blank=True, choices=[('email', 'Електронна пошта'), ('phone', 'Телефон'), ('email_phone', 'Електронна пошта або телефон, чат, елекронна пошта')], max_length=50),
        ),
    ]
